/*
SSM (Secure Storage Manager) API

Testing KeyManagementAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package models

import (
	"context"
	"testing"

	openapiclient "github.com/networkgcorefullcode/ssm/models"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_KeyManagementAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test KeyManagementAPIService GenerateAESKey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.KeyManagementAPI.GenerateAESKey(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KeyManagementAPIService StoreKey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.KeyManagementAPI.StoreKey(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
