package constants

const (
	ACTION_ENCRYPT_DATA      = "ENCRYPT_DATA"
	ACTION_DECRYPT_DATA      = "DECRYPT_DATA"
	ACTION_ENCRYPT_GCM       = "ENCRYPT_AES_GCM"
	ACTION_DECRYPT_GCM       = "DECRYPT_AES_GCM"
	ACTION_GENERATE_AES_KEY  = "GENERATE_AES_KEY"
	ACTION_GENERATE_DES_KEY  = "GENERATE_DES_KEY"
	ACTION_GENERATE_DES3_KEY = "GENERATE_DES3_KEY"
	ACTION_STORE_KEY         = "STORE_KEY"
	ACTION_UPDATE_KEY        = "UPDATE_KEY"
	ACTION_DELETE_KEY        = "DELETE_KEY"
	ACTION_GET_KEY           = "GET_KEY"
	ACTION_GET_KEYS          = "GET_KEYS"
	ACTION_GET_ALL_KEYS      = "GET_ALL_KEYS"
	ACTION_HEALTH_CHECK      = "HEALTH_CHECK"
	ACTION_USER_LOGIN        = "USER_LOGIN"

	USER_UDM        = "udm"
	USER_WEBCONSOLE = "webconsole"
)

// ActionList keep all action for the http api, if you add new action you must add that action here
var ActionList []string = []string{
	ACTION_ENCRYPT_DATA,
	ACTION_DECRYPT_DATA,
	ACTION_GENERATE_AES_KEY,
	ACTION_GENERATE_DES_KEY,
	ACTION_GENERATE_DES3_KEY,
	ACTION_STORE_KEY,
	ACTION_UPDATE_KEY,
	ACTION_DELETE_KEY,
	ACTION_GET_KEY,
	ACTION_GET_KEYS,
	ACTION_GET_ALL_KEYS,
	ACTION_HEALTH_CHECK,
	ACTION_USER_LOGIN,
	ACTION_ENCRYPT_GCM,
	ACTION_DECRYPT_GCM,
}
