/*
SSM (Secure Storage Manager) API

API for secure cryptographic key management using PKCS#11 and HSM.  SSM provides secure operations for: - AES, DES, DES3 key generation - Data encryption and decryption - Key storage and management - HSM/SoftHSM integration  ## Authentication The API works through Unix Domain Sockets for enhanced security. Also supports HTTPS with TLS certificates.  ## Data Formats - All binary data (plaintext, ciphertext, IV) should be in Base64/Hex - Responses include timestamps in RFC3339 format - Errors follow RFC 7807 standard (Problem Details)

API version: 1.0.0
Contact: support@yourorganization.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// UpdateKeyRequest
type UpdateKeyRequest struct {
	// Label of the key to update
	KeyLabel string `json:"key_label"`
	// Key identifier
	Id int32 `json:"id"`
	// New key value in hexadecimal format
	KeyValue string `json:"key_value"`
	// Type of cryptographic key
	KeyType string `json:"key_type"`
}
