/*
SSM (Secure Storage Manager) API

API para gestión segura de claves criptográficas usando PKCS#11 y HSM.

API version: 1.0.0
Contact: support@yourorganization.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// UpdateKeyRequest struct for UpdateKeyRequest
type UpdateKeyRequest struct {
	// Etiqueta de la clave a actualizar
	KeyLabel string `json:"key_label"`
	// Identificador único
	Id string `json:"id"`
	// Nuevo valor de la clave en hexadecimal
	KeyValue string `json:"key_value"`
	// Tipo de clave (AES, DES3, DES)
	KeyType string `json:"key_type"`
}
