/*
SSM (Secure Storage Manager) API

API para gestión segura de claves criptográficas usando PKCS#11 y HSM.

API version: 1.0.0
Contact: support@yourorganization.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

type DeleteKeyRequest struct {
	// Etiqueta de la clave a eliminar
	KeyLabel string `json:"key_label"`
	// Identificador único (opcional)
	Id string `json:"id,omitempty"`
}
