/*
SSM (Secure Storage Manager) API

API para gestión segura de claves criptográficas usando PKCS#11 y HSM.

API version: 1.0.0
Contact: support@yourorganization.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

type DeleteKeyResponse struct {
	// Mensaje de confirmación
	Message string `json:"message"`
	// Etiqueta de la clave eliminada
	KeyLabel string `json:"key_label"`
}
