/*
SSM (Secure Storage Manager) API

API para gestión segura de claves criptográficas usando PKCS#11 y HSM.

API version: 1.0.0
Contact: support@yourorganization.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DeleteKeyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteKeyRequest{}

// DeleteKeyRequest struct for DeleteKeyRequest
type DeleteKeyRequest struct {
	// Etiqueta de la clave a eliminar
	KeyLabel string `json:"key_label"`
	// Identificador único (opcional)
	Id string `json:"id,omitempty"`
}

type _DeleteKeyRequest DeleteKeyRequest

// NewDeleteKeyRequest instantiates a new DeleteKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteKeyRequest(keyLabel string) *DeleteKeyRequest {
	this := DeleteKeyRequest{}
	this.KeyLabel = keyLabel
	return &this
}

// NewDeleteKeyRequestWithDefaults instantiates a new DeleteKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but not the ones where the parameter is required
func NewDeleteKeyRequestWithDefaults() *DeleteKeyRequest {
	this := DeleteKeyRequest{}
	return &this
}

// GetKeyLabel returns the KeyLabel field value
func (o *DeleteKeyRequest) GetKeyLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyLabel
}

// GetKeyLabelOk returns a tuple with the KeyLabel field value
// and a boolean to check if the value has been set.
func (o *DeleteKeyRequest) GetKeyLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyLabel, true
}

// SetKeyLabel sets field value
func (o *DeleteKeyRequest) SetKeyLabel(v string) {
	o.KeyLabel = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DeleteKeyRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteKeyRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return &o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DeleteKeyRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DeleteKeyRequest) SetId(v string) {
	o.Id = v
}

func (o DeleteKeyRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteKeyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key_label"] = o.KeyLabel
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

func (o *DeleteKeyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key_label",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteKeyRequest := _DeleteKeyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteKeyRequest)

	if err != nil {
		return err
	}

	*o = DeleteKeyRequest(varDeleteKeyRequest)

	return err
}

type NullableDeleteKeyRequest struct {
	value *DeleteKeyRequest
	isSet bool
}

func (v NullableDeleteKeyRequest) Get() *DeleteKeyRequest {
	return v.value
}

func (v *NullableDeleteKeyRequest) Set(val *DeleteKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteKeyRequest(val *DeleteKeyRequest) *NullableDeleteKeyRequest {
	return &NullableDeleteKeyRequest{value: val, isSet: true}
}

func (v NullableDeleteKeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteKeyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
