/*
SSM (Secure Storage Manager) API

API for secure cryptographic key management using PKCS#11 and HSM.  SSM provides secure operations for: - AES, DES, DES3 key generation - Data encryption and decryption - Key storage and management - HSM/SoftHSM integration  ## Authentication The API works through Unix Domain Sockets for enhanced security. Also supports HTTPS with TLS certificates.  ## Data Formats - All binary data (plaintext, ciphertext, IV) should be in Base64/Hex - Responses include timestamps in RFC3339 format - Errors follow RFC 7807 standard (Problem Details)

API version: 1.0.0
Contact: support@yourorganization.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ProblemDetails Detalles de error según RFC 7807
type ProblemDetails struct {
	// Short title of the problem
	Title string `json:"title"`
	// Detailed description of the problem
	Detail string `json:"detail"`
	// HTTP status code
	Status int32 `json:"status"`
	// Internal error code
	Error string `json:"error"`
	// URI identifying the specific occurrence
	Instance string `json:"instance"`
}
