/*
SSM (Secure Storage Manager) API

API para gestión segura de claves criptográficas usando PKCS#11 y HSM.  El SSM proporciona operaciones seguras de: - Generación de claves AES - Cifrado y descifrado de datos - Almacenamiento de claves - Gestión mediante HSM/SoftHSM  ## Autenticación La API funciona a través de Unix Domain Sockets para mayor seguridad. Tambien da soporte a HTTPS con certificados TLS. No implementado aun.  ## Formatos de datos - Todos los datos binarios (plaintext, ciphertext, IV) deben estar en Base64 - Las respuestas incluyen timestamps en formato RFC3339 - Los errores siguen el estándar RFC 7807 (Problem Details)

API version: 1.0.0
Contact: support@yourorganization.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package models

import "time"

// EncryptResponse struct for EncryptResponse
type EncryptResponse struct {
	// Datos cifrados en Base64
	Cipher *string `json:"cipher,omitempty"`
	// Vector de inicialización en Base64
	Iv *string `json:"iv,omitempty"`
	// Indica si la operación fue exitosa
	Ok *bool `json:"ok,omitempty"`
	// Timestamp de creación en RFC3339
	TimeCreated *time.Time `json:"time_created,omitempty"`
	// Timestamp de actualización en RFC3339
	TimeUpdated *time.Time `json:"time_updated,omitempty"`
}
