/*
SSM (Secure Storage Manager) API

API para gestión segura de claves criptográficas usando PKCS#11 y HSM.

API version: 1.0.0
Contact: support@yourorganization.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// UpdateKeyResponse struct for UpdateKeyResponse
type UpdateKeyResponse struct {
	// Mensaje de confirmación
	Message string `json:"message"`
	// Nuevo handle de la clave actualizada
	Handle uint `json:"handle"`
	// Etiqueta de la clave actualizada
	KeyLabel string `json:"key_label"`
	// Clave encriptada (opcional)
	CipherKey *string `json:"cipher_key,omitempty"`
}
