/*
SSM (Secure Storage Manager) API

API para gestión segura de claves criptográficas usando PKCS#11 y HSM.  El SSM proporciona operaciones seguras de: - Generación de claves AES - Cifrado y descifrado de datos - Almacenamiento de claves - Gestión mediante HSM/SoftHSM  ## Autenticación La API funciona a través de Unix Domain Sockets para mayor seguridad. Tambien da soporte a HTTPS con certificados TLS. No implementado aun.  ## Formatos de datos - Todos los datos binarios (plaintext, ciphertext, IV) deben estar en Base64 - Las respuestas incluyen timestamps en formato RFC3339 - Los errores siguen el estándar RFC 7807 (Problem Details)

API version: 1.0.0
Contact: support@yourorganization.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// GenAESKeyResponse struct for GenAESKeyResponse
type GenAESKeyResponse struct {
	// Handle de la clave en el HSM
	Handle uint `json:"handle,omitempty"`
	// Etiqueta de la clave generada
	Label *string `json:"label,omitempty"`
	// ID de la clave generada
	Id *string `json:"id,omitempty"`
	// Tamaño de la clave generada
	Bits *int `json:"bits,omitempty"`
}
