/*
SSM (Secure Storage Manager) API

API para gestión segura de claves criptográficas usando PKCS#11 y HSM.

API version: 1.0.0
Contact: support@yourorganization.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateKeyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateKeyRequest{}

// UpdateKeyRequest struct for UpdateKeyRequest
type UpdateKeyRequest struct {
	// Etiqueta de la clave a actualizar
	KeyLabel string `json:"key_label"`
	// Identificador único
	Id string `json:"id"`
	// Nuevo valor de la clave en hexadecimal
	KeyValue string `json:"key_value"`
	// Tipo de clave (AES, DES3, DES)
	KeyType string `json:"key_type"`
}

type _UpdateKeyRequest UpdateKeyRequest

// NewUpdateKeyRequest instantiates a new UpdateKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateKeyRequest(keyLabel string, id string, keyValue string, keyType string) *UpdateKeyRequest {
	this := UpdateKeyRequest{}
	this.KeyLabel = keyLabel
	this.Id = id
	this.KeyValue = keyValue
	this.KeyType = keyType
	return &this
}

// NewUpdateKeyRequestWithDefaults instantiates a new UpdateKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but not the ones where the parameter is required
func NewUpdateKeyRequestWithDefaults() *UpdateKeyRequest {
	this := UpdateKeyRequest{}
	return &this
}

// GetKeyLabel returns the KeyLabel field value
func (o *UpdateKeyRequest) GetKeyLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyLabel
}

// GetKeyLabelOk returns a tuple with the KeyLabel field value
// and a boolean to check if the value has been set.
func (o *UpdateKeyRequest) GetKeyLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyLabel, true
}

// SetKeyLabel sets field value
func (o *UpdateKeyRequest) SetKeyLabel(v string) {
	o.KeyLabel = v
}

// GetId returns the Id field value
func (o *UpdateKeyRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateKeyRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateKeyRequest) SetId(v string) {
	o.Id = v
}

// GetKeyValue returns the KeyValue field value
func (o *UpdateKeyRequest) GetKeyValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyValue
}

// GetKeyValueOk returns a tuple with the KeyValue field value
// and a boolean to check if the value has been set.
func (o *UpdateKeyRequest) GetKeyValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyValue, true
}

// SetKeyValue sets field value
func (o *UpdateKeyRequest) SetKeyValue(v string) {
	o.KeyValue = v
}

// GetKeyType returns the KeyType field value
func (o *UpdateKeyRequest) GetKeyType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyType
}

// GetKeyTypeOk returns a tuple with the KeyType field value
// and a boolean to check if the value has been set.
func (o *UpdateKeyRequest) GetKeyTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyType, true
}

// SetKeyType sets field value
func (o *UpdateKeyRequest) SetKeyType(v string) {
	o.KeyType = v
}

func (o UpdateKeyRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateKeyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key_label"] = o.KeyLabel
	toSerialize["id"] = o.Id
	toSerialize["key_value"] = o.KeyValue
	toSerialize["key_type"] = o.KeyType
	return toSerialize, nil
}

func (o *UpdateKeyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key_label",
		"id",
		"key_value",
		"key_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateKeyRequest := _UpdateKeyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateKeyRequest)

	if err != nil {
		return err
	}

	*o = UpdateKeyRequest(varUpdateKeyRequest)

	return err
}

type NullableUpdateKeyRequest struct {
	value *UpdateKeyRequest
	isSet bool
}

func (v NullableUpdateKeyRequest) Get() *UpdateKeyRequest {
	return v.value
}

func (v *NullableUpdateKeyRequest) Set(val *UpdateKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateKeyRequest(val *UpdateKeyRequest) *NullableUpdateKeyRequest {
	return &NullableUpdateKeyRequest{value: val, isSet: true}
}

func (v NullableUpdateKeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateKeyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
