/*
SSM (Secure Storage Manager) API

API for secure cryptographic key management using PKCS#11 and HSM.  SSM provides secure operations for: - AES, DES, DES3 key generation - Data encryption and decryption - Key storage and management - HSM/SoftHSM integration  ## Authentication The API works through Unix Domain Sockets for enhanced security. Also supports HTTPS with TLS certificates.  ## Data Formats - All binary data (plaintext, ciphertext, IV) should be in Base64/Hex - Responses include timestamps in RFC3339 format - Errors follow RFC 7807 standard (Problem Details)

API version: 1.0.0
Contact: support@yourorganization.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"time"
)

// EncryptResponse
type EncryptResponse struct {
	// Encrypted data in hexadecimal
	Cipher string `json:"cipher"`
	// Initialization vector in hexadecimal
	Iv string `json:"iv"`
	// Id key that used to encrypt plan data
	Id int32 `json:"id"`
	// Indicates if the operation was successful
	Ok bool `json:"ok"`
	// Creation timestamp in RFC3339
	TimeCreated time.Time `json:"time_created"`
	// Update timestamp in RFC3339
	TimeUpdated time.Time `json:"time_updated"`
}
