/*
SSM (Secure Storage Manager) API

API for secure cryptographic key management using PKCS#11 and HSM.  SSM provides secure operations for: - AES, DES, DES3 key generation - Data encryption and decryption - Key storage and management - HSM/SoftHSM integration  ## Authentication The API supports JWT Bearer tokens and API keys for authentication. Obtain a JWT token using the `/login` endpoint.  ## Data Formats - All binary data (plaintext, ciphertext, IV) should be in Base64/Hex - Responses include timestamps in RFC3339 format - Errors follow RFC 7807 standard (Problem Details)

API version: 1.0.0
Contact: support@yourorganization.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import "time"

// DecryptAESGCMResponse - Response for AES-GCM decryption
type DecryptAESGCMResponse struct {
	// Decrypted plaintext data in hexadecimal
	Plain string `json:"plain"`
	// ID of the key that was used to decrypt the data
	Id int32 `json:"id,omitempty"`
	// Indicates if the operation was successful
	Ok bool `json:"ok"`
	// Creation timestamp in RFC3339 format
	TimeCreated time.Time `json:"time_created,omitempty"`
	// Update timestamp in RFC3339 format
	TimeUpdated time.Time `json:"time_updated,omitempty"`
}
